application: helloworld
version: 47
runtime: php55
api_version: 1

handlers:
- url: /.*
  script: public/index.php

env_variables:
  debug:  true
  authDriver: cookie
  theme: default
  timeZone: PRC     
 
